### PR TITLE
Added ability to enable metadata functionality sitewide

### PR DESCRIPTION
**Pull request by ichim-david**
This pull request has two major changes:
1. A performance improvement where I save the old content types values within Annotation
   in order to avoid that catalog search for all content types tagged just so that you know
   what is new and what is old when you change the content type listing
2. I've added a new Boolean field **enabled_sitewide** which if enabled will activate the content
   metatags globally bypassing the need to enabled and disable manual per content type and object
  If you disable the option than the package continues to work as it worked before the addition of
  this feature.

The reason for this feature is because when you have a portal with a large number of documents (100,000+) attempting to do a catalog search to reindex all is something that takes a long time.
Another reason for adding this feature is because in Plone 5 you have a sitewide enable or disable
of these "social media" tags without any interface checks and reindexes which makes it easier to
use on sites with many objects.

Let me know if you need anything changes and I will try to reply ASAP

### CODE REVIEW

**Comment by erral** [comment]
I see I merged the last pull-request here...

I basically agree with your changes, specially the one to enable sitewide the metatags...

**Comment by erral** [comment]
I can merge it if you want. 

Then we will need to ping people from redturtle to make a release. on pypi the product is owned by @amleczko and @massimoazzolini can you give someone else rights on pypi?

**Comment by ichim-david** [comment]
@erral that would be great both on pypi front and the merging
but before you do that I will add a history entry for this pull request
work as I intended to do so after I got any feedback from having this pull request
open

**Comment by erral** [comment]
@ichim-david is this ready?

**Comment by ichim-david** [comment]
@erral  yes it is I have added the history entry that i've mentioned yesterday

**Pull request merged**
